# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

before_install:
  - sudo apt-get install -y python3-pip python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip install PyGithub
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/travis/travis/docker-build
  - chmod +x docker-build
 
install:
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build autotools

deploy:
  provider: script
  script: ./docker-build --name ${DISTRO} --verbose --config .travis.yml --release
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^v.*$ && $DISTRO == fedora:29"

env:
  - DISTRO="archlinux/base"
  - DISTRO="debian:sid"
  - DISTRO="fedora:29"
  - DISTRO="ubuntu:18.10"

##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    - gcc
    - git # Required to generate the ChangeLog file
    - gtk3
    - intltool
    - libnotify
    - libwnck3
    - make
    - mate-common
    - which

  debian:
    - git # Required to generate the ChangeLog file
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - libcanberra-gtk3-dev
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgail-3-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libnotify-dev
    - libpango1.0-dev
    - libstartup-notification0-dev
    - libwnck-3-dev
    - libx11-dev
    - libxml2-dev
    - mate-common
    - quilt
    - shared-mime-info

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/caja.git/
    - git # Required to generate the ChangeLog file
    - desktop-file-utils
    - file
    - libcanberra-devel
    - libnotify-devel
    - libwnck3-devel
    - mate-common
    - mate-desktop-devel

  ubuntu:
    - git # Required to generate the ChangeLog file
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - libcanberra-gtk3-dev
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgail-3-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libnotify-dev
    - libpango1.0-dev
    - libstartup-notification0-dev
    - libwnck-3-dev
    - libx11-dev
    - libxml2-dev
    - mate-common
    - quilt
    - shared-mime-info

variables:
  - CFLAGS="-Wall -Werror=format-security"

after_scripts:
  - make distcheck

releases:
  draft: False
  prerelease: False
  checksum: True
  base_version: 1.20.0
  file_glob: True
  files: mate-notification-daemon-*.tar.xz
  web_hooks:
    - http://pub.mate-desktop.org/releases/
